controllers/InstallController.php
<?php
/**
* Rights installation controller class file.
*
* @author OncallSofware
* @copyright OncallSoftware
* @since 
*/
class InstallController extends Controller
{
	/**
	* @property RAuthorizer
	*/
	private $_authorizer;
	/**
	* @property RInstaller
	*/
	private $_installer;
	private $_accessControlRules;

	/**
	* Initializes the controller.
	*/
	public function init() {

		if( $this->module->install!==true )
			$this->redirect(Yii::app()->homeUrl);

		$this->_authorizer = $this->module->getAuthorizer();
		$this->_installer = $this->module->getInstaller();
		$this->layout = $this->module->layout;
		$this->defaultAction = 'start';
	}
	/**
	 * @return array action filters
	 */
	public function filters() {
		return array(
		  'accessControl', // perform access control
		);
	}
	/**
	* limit this controller to superusers!
	* @return array access control rules
	*/
	public function accessRules() {
		return array(
			array('allow', // Allow superusers to install qbo module
				'users'		=> $this->_authorizer->getSuperusers(),				
			),
			array('deny', // Deny all users
				'users'=>array('*'),
				'message'	=> 'Quickbooks Online module not installed. Superuser privilages are required to install Quickbooks module.'
			),
		);
	}
	/**
	* Installs the module.
	*/
	public function actionRun()	{
		// Make sure that the module is not already installed.
		if( isset($_GET['confirm'])===true || $this->_installer->installed===false )
		{
			// Run the installer and check for an error.
			if( $this->_installer->run()===QboInstaller::ERROR_NONE )
			{
				Yii::app()->user->setFlash('success', "Database tables setup complete!");
				$this->redirect(array('install/ready'));
			}
			Yii::app()->user->setFlash('error', "Unable to create database schema. Please review logs.");
            // Redirect to the error page.
			$this->redirect(array('install/error'));
		}
		// Module is already istalled.
		else
		{
			$this->redirect(array('install/confirm'));
		}
	}

	/**
	* Displays the install ready page.
	*/
	public function actionReady() {
		$this->render('ready');
	}

    /**
	* Displays the install error.
	*/
	public function actionError() {
		$this->render('error');
	}

    /**
	* Displays the confirm ready page.
	*/
	public function actionConfirm() {
		$this->render('confirm');
	}
	/**
	* The entry point for the install process
	*/ 
	public function actionStart() {
		// if it is installed it will notify user
		if ( $this->_installer->getInstalled() ) {
			$this->render("confirm");
		} else {	
			$this->render("index");
		}
	}
}

views/install/confirm.php
<div id="installer" class="confirm">

	<h2><?php echo Yii::t('install', 'Install Quickbooks Online Module'); ?></h2>

	<p class="red-text">
		<?php echo Yii::t('install', 'Qbo Module is already installed!'); ?>
	</p>

	<p><?php echo Yii::t('install', 'Please confirm if you wish to reinstall.'); ?></p>

	<p>
		<?php echo CHtml::link(Yii::t('install', 'Yes'), array('install/run', 'confirm'=>1)); ?> /
		<?php echo CHtml::link(Yii::t('install', 'No'), Yii::app()->homeUrl); ?>
	</p>

	<p class="info"><?php echo Yii::t('install', 'Notice: All your mapped quickbooks connections and data will be lost.'); ?></p>

</div>

views/install/error.php
<div id="installer" class="error">

	<h2><?php echo Yii::t('install', 'Error'); ?></h2>

	<p class="red-text">
		<?php echo Yii::t('install', 'An error occurred while installing Quickbooks Online module.'); ?>
	</p>

    <p>
		<?php echo Yii::t('install', 'Please try again or review the module code.') ;?>
	</p>

</div>

views/install/index.php
<div id="installer" class="confirm">

	<h2><?php echo Yii::t('install', 'Install Quickbooks Online Module'); ?></h2>

	<p><?php echo Yii::t('install', 'Please confirm if you wish to install this module.'); ?></p>

	<p>
		<?php echo CHtml::link(Yii::t('install', 'Yes'), array('install/run', 'confirm'=>1)); ?> /
		<?php echo CHtml::link(Yii::t('install', 'No'), Yii::app()->homeUrl); ?>
	</p>

</div>

views/install/ready.php
<div id="installer" class="ready">

	<h2><?php echo Yii::t('install', 'Congratulations!'); ?></h2>

	<p class="green-text">
		<?php echo Yii::t('install', 'Quickbooks Online (Qbo) has been installed succesfully.'); ?>
	</p>

	<p>
		<?php echo Yii::t('install', 'You can start by linking this user to your online quickbooks account.') ;?>
		<?php echo CHtml::link(Yii::t('install', 'here'), array('/qbo')); ?>.
	</p>

</div>